### PR TITLE
Homework17

### PR DESCRIPTION
**Pull request by Angelina0504**
it should works

### CODE REVIEW

**Comment by Angelina0504** [comment]
please explain why this test is not working?

**Comment by Berichicko** [comment]
> please explain why this test is not working?

You got this problem, please correct it. Please finish your homework.

image

HINT

Test failed(yellow). If at least one test receives this status, then all its parents are marked as failed.

For example

Test failed_en

image

`String expectedSongAddedMessage = "Added 1 song into \"Test Pro Playlist.\"";`

**Comment by Angelina0504** [comment]
please help me with this homework, I spend 20 hours, and I can not understand what is wrong with this test. I did change :"Added 1 song into", but it did not work. This test is not running. ?????

**Comment by Angelina0504** [comment]
Any other suggestions. Thanks

**Comment by Angelina0504** [comment]
Also, i checked in LoginTests.java all the tests are running. what other issues it could have?

**Comment by Berichicko** [comment]
Здравствуйте!

Тесты проходят, когда добавляешь новую песню в плейлист, когда песня уже есть, то не появляется окно с сообщением что песня добавлена в плейлист и тест падает.

Не переживайте! У вас все хорошо!

В будущих уроках: научитесь удалять и создавать плейлист.
image

**Pull request merged**
